language: ruby

sudo: false

before_install:
  - gem update --system
  # bundler installation needed for jruby-head
  # https://github.com/travis-ci/travis-ci/issues/5861
  - gem install bundler

script: "bundle exec rubytest -Ilib test/ --verbose"
bundler_args: --without guard

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.4
  - 2.3.2
  - 2.4.0
  - rbx
  - jruby-9.0.5.0
  - jruby-9.1.5.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: rbx

cache: bundler

# Use Java 8 for jruby to fix some Java 7 bugs.
addons:
  apt:
    packages:
      - oracle-java8-set-default
